/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import edu.princeton.cs.algs4.Draw;

import java.awt.*;

public class App {

    public static void main(String[] args) {

        Draw draw = new Draw();
        draw.setCanvasSize(800,800);
        draw.setYscale(0,800);
        draw.setXscale(0,800);
        draw.circle(.4,.4,.3);

        draw.setPenColor(Color.red);
        draw.filledCircle(400, 400, 50);
        draw.rectangle(20, 20, 400, 400);


    }
}
